### ISSUE TITLE
Docker location

### ISSUE THREAD

**Issue by lferezy4** [valeriansaliou/vigil#11]
i just tried to install vigil on docker and i cannot find the location of where it intalled vigil too.

**Comment by lferezy4** [comment]
So how do i configure vigil or run it..

**Comment by Frederik-Baetens** [comment]
You can put the config file in the docker image with the docker COPY keyword, but if you don't know how to use docker, I suggest running vigil trough cargo.

**Comment by valeriansaliou** [comment]
Hi @lferezy4,

As explained in the README.md file, you can simply pull the image from Dockerhub via the command:

`docker pull valeriansaliou/vigil:v1.4.0`

And then run Vigil on port 8080 (that you will need your Apache or NGINX to proxy to):

`docker run -p 8080:8080 -v /path/to/your/vigil/config.cfg:/etc/vigil.cfg valeriansaliou/vigil:v1.4.0`

You need to provide a path to your `vigil.cfg` file, that's stored outside of Docker (ie. on the system running Docker, not the container). You can find a working example of this file in the Git repository.

Just ensure that:

* server.inet is set to 0.0.0.0:8080 (this lets Vigil be reached from outside the container)
* assets.path is set to ./res/assets/ (this refers to an internal path in the container, as the assets are contained there)

Cheers.

**Comment by lferezy4** [comment]
This is a separate issue from docker but im trying to install it via cargo and im getting the following errors 

`   Compiling rayon-core v1.4.1
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `rayon-core`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `vigil-server v1.4.0`, intermediate artifacts can be found at `/tmp/cargo-installXNuRW6`

Caused by:
  build failed`

**Comment by zllovesuki** [comment]
@lferezy4 you need to have build tools installed on the machine. If you building on a Mac, use `brew`. If you building on GNU/Linux, depending on the distro, you need `make` `gcc` and a host of other stuff.

**Comment by valeriansaliou** [comment]
Considering this closed; please re-open if the issue is still happening.
