### ISSUE TITLE
Unable to run container

### ISSUE THREAD

**Issue by ZAM-** [valeriansaliou/vigil#111]
I'm getting the following error. Is the recent docker build working for anyone else?

```
thread 'main' panicked at 'cannot find config file: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/config/reader.rs:22:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cbrandlehner** [comment]
@ZAM- the error indicates that the code can not access the config file.
Make sure that 

- the config file exists, 
- you are mapping the config file into the container using the "docker -v ...." option and 
- that access rights to the config file are sufficient.

**Comment by ZAM-** [comment]
Thank you!
