### ISSUE TITLE
Twilio 400 Bad Request

### ISSUE THREAD

**Issue by lnfel** [valeriansaliou/vigil#122]
> OS: MacOS
vigil-server version: 1.24.0
using the project template from master branch

Hi, I was trying out vigil for the first time and been following the setup instructions seen on README.

I have successfully sent an email notification through Mailtrap's smtp but Twilio on the other hand is not working as expected.

Here is my `config.cfg`:
```rust
[notify.twilio]

to = [
  "+<My phone number>",
]

service_sid = "<Messaging Service SID>"
account_sid = "<My Account SID (live)>"
auth_token = "<My Account Token (live)>"

reminders_only = false
```

Here is the log related to the issue:
```
(INFO) - ran poll probe operation
(DEBUG) - flushed 521 bytes
(DEBUG) - parsed 17 headers
(DEBUG) - incoming body is content-length (159 bytes)
(DEBUG) - incoming body completed
(DEBUG) - pooling idle connection for ("https", api.twilio.com)
(DEBUG) - response '400 Bad Request' for https://api.twilio.com/2010-04-01/Accounts/<My Account SID (Live)>/Messages.json
(DEBUG) - dispatch twilio notification attempt: #2
(DEBUG) - will send Twilio notification with message: Startup alert for: My Website Status
```

I tried to check `src/notifier/twilio.rs` and there seems nothing wrong with how the post request is built.

Is there anything I missed for twilio to work?

**Comment by valeriansaliou** [comment]
Hey there, https://status.crisp.chat is running Vigil 1.24.0 and we had a pretty nasty downtime yesterday, which involved sending SMS reminders which worked, so I'm pretty sure Twilio works OK.

Can you check that all formats are correct for the SIDs and tokens and phone number?

**Comment by lnfel** [comment]
> Can you check that all formats are correct for the SIDs and tokens and phone number?

Oh god, I just checked the phone number and my country code is wrong, thank you it is now working!
