### ISSUE TITLE
Domain Name Setup - HTTPS

### ISSUE THREAD

**Issue by ProMailx** [valeriansaliou/vigil#124]
I'm currently visiting the status page with IP address or HTTP(non https) , how do I set up so that it can be accessed from like e.g. https://status.domain.com ? 

Current A Record 
Key : status
Value : IP Address

Thank you!

**Comment by valeriansaliou** [comment]
You need to setup a reverse proxy such as NGINX in front of Vigil so that users can access it over SSL.
