### ISSUE TITLE
where do I buy you a cup of coffee? ☕

### ISSUE THREAD

**Issue by zllovesuki** [valeriansaliou/vigil#14]
Awesome project! What if the community wants to donate a cup of coffee (or beer), is there a link for that?

**Comment by valeriansaliou** [comment]
Hi! Ahah, that's lovely. Never got offered that on GitHub, here's a link: https://www.buymeacoffee.com/valeriansaliou

Thank you 🚀

**Comment by valeriansaliou** [comment]
Thanks a ton!
