### ISSUE TITLE
Vigil causes error messages to show up in Caddy's logs

### ISSUE THREAD

**Issue by whalehub** [valeriansaliou/vigil#15]
I'm currently hosting my sites behind the reverse proxy Caddy and I'm using Vigil to poll the status of these sites as HTTP targets. Now, the problem is that whenever Vigil polls a site, the following error message shows up in Caddy's logs:

```
2018/12/19 23:14:51 Unsolicited response received on idle HTTP channel starting with "0\r\n\r\n"; err=<nil>
```

The error message appears to be harmless in the sense that both Vigil and Caddy work fine in spite of it, but I still think that it's something that should be looked into because something seems to be wrong with the HTTP request that Vigil sends out when it polls a site.

I found some information about this error message on [this](https://github.com/golang/go/issues/19895) Golang issue.

**Comment by whalehub** [comment]
@valeriansaliou Sure thing!

**Comment by valeriansaliou** [comment]
`v1.7.0` has just been released; Docker hub image is being built & uploaded.

**Comment by valeriansaliou** [comment]
Now tracking the issue on https://github.com/seanmonstar/reqwest/issues/405 ; closing this one.

**Comment by whalehub** [comment]
@valeriansaliou Can you reopen this issue? Issue #405 was closed since the dev of reqwest thinks that the problem lies with Vigil instead of reqwest.
