### ISSUE TITLE
Vigil reporting incorrect outage

### ISSUE THREAD

**Issue by richthegeek** [valeriansaliou/vigil#17]
I'm trying this out locally to replace our limited home-spun solution.

I have it working fine for a system which returns a JSON body, but another one which simply returns "ok" is not behaving.

The config that fails is:
```
[[probe.service.node]]
id = "block.veoo.com"
label = "block.veoo.com access"
mode = "poll"
replicas = ["https://block.veoo.com/health_check"]
```

This URL returns with GET:
```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 2
Date: Tue, 29 Jan 2019 23:21:46 GMT
Connection: keep-alive

ok
```

So I'm not sure why it's reporting as failed. Any ideas?

**Comment by valeriansaliou** [comment]
Did you try if a HEAD request also returns 200? Vigil performs HEADs not GETs to probe HTTP endpoints.

--

Valerian Saliou
CTO at Crisp

**Comment by richthegeek** [comment]
```
> HEAD /health_check HTTP/1.1
> Host: block.veoo.com
> User-Agent: insomnia/6.3.2
> Accept: */*
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Content-Length: 2
< Date: Tue, 29 Jan 2019 23:34:16 GMT
< Connection: keep-alive

* Connection #0 to host block.veoo.com left intact
```

Seems like it also returned 200 with a HEAD request

**Comment by richthegeek** [comment]
Ok so looking at the logs (previously there were none as my log-level was `error`) I saw that it was returning 401 Unauthorized to the request.

`http://block.veoo.com/health_check?1548809127`

The service it's checking is lazily configured to auth every route except _exactly_ /health_check, so the extra query part was breaking it.

**Comment by valeriansaliou** [comment]
Ah, yes. Vigil auto appends a cache buster to make sure it bypasses any CDN cache or NGINX cache while checking. This ensures the request hits the underlying backend service if any. This cannot be changed.

--

Valerian Saliou
CTO at Crisp

**Comment by valeriansaliou** [comment]
Did you manage to solve this issue on your end?
