### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by lferezy4** [valeriansaliou/vigil#2]
getting this error when i try to install 

```
[root@status ~]# cargo install vigil-server
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing vigil-server v1.1.2
   Compiling serde v1.0.27
error: the optimizations s or z are only accepted on the nightly compiler

error: failed to compile `vigil-server v1.1.2`, intermediate artifacts can be found at `/tmp/cargo-install.P2pvoDcsgJnE`

Caused by:
  Could not compile `serde`.

To learn more, run the command again with --verbose.
[root@status ~]#
```

**Comment by valeriansaliou** [comment]
Ah, you need to use the Rust `nightly` compiler (fetch the latest version from eg. yesterday).

**Comment by lferezy4** [comment]
can you tell me the command i would run? i am not used to linux

**Comment by valeriansaliou** [comment]
Check: https://www.rustup.rs

Install `nightly` when you run the setup script.

**Comment by lferezy4** [comment]
Wait so this is for windows?

**Comment by valeriansaliou** [comment]
You need to compile this on the same Linux distribution you want the binary to run on, as it will be dynamically linked to your system libraries. Otherwise try compiling it w/ a MUSL compiler.

**Comment by valeriansaliou** [comment]
Hi, a Docker image has just been released. This will help fix your install issues!
