### ISSUE TITLE
Be able to call an endpoint to retrieve node information/health

### ISSUE THREAD

**Issue by yatiac** [valeriansaliou/vigil#20]
It would be a nice to have an endpoint per probe/node that you can call and retrieve its health in a standard form.

Do you have something like this in mind? What do you think about this?

**Comment by valeriansaliou** [comment]
You can already do this with Vigil Reporter. See [node-vigil-reporter](https://github.com/valeriansaliou/node-vigil-reporter/) for an example library.

**Comment by yatiac** [comment]
Correct me if I am wrong, this is for manual reporting from my application or is it to retrieve node information from Vigil ?

**Comment by valeriansaliou** [comment]
Ah, I think I got it wrong. To retrieve information (I think this is what you asked rather, sorry), you can follow #4 which is due to be done soon.

**Comment by yatiac** [comment]
Thanks,  I will keep an eye on that. Will close this for now.
