### ISSUE TITLE
Execute actions based on health changes

### ISSUE THREAD

**Issue by yatiac** [valeriansaliou/vigil#21]
What do you think about having an option to execute actions based on health changes? It could be just as simple as executing a power shell script (let's say, to restart a service).

I guess for now there are ways to do this using slack integrations but could be nice to have it directly in vigil.

**Comment by valeriansaliou** [comment]
Hi! I think it would make Vigil more complex, which is not in the philosophy of the project. Though, I'll soon be coming up with an RSS feed feature (see #4 issue), which would allow a custom bot of yours to periodically fetch the detailed status eg. every 10 seconds and thus execute a script based on this.

**Comment by yatiac** [comment]
Thanks for your prompt response , I guess I can close this now.
