### ISSUE TITLE
Getting errors when trying to build

### ISSUE THREAD

**Issue by yatiac** [valeriansaliou/vigil#22]
Hi, I am having 2 errors when trying to build with cargo, I am using rust `nightly-2018-12-14` as instructed.

The errors are:
```

- imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
```
```
- use of unstable library feature 'duration_as_u128' (see issue #50202)

```

Am I doing something wrong? (I have never used cargo so I don't really know how to troubleshoot, but if you need any more info, let me know)

**Comment by valeriansaliou** [comment]
Hi! Can you try w/ latest nightly?

**Comment by yatiac** [comment]
Latest nightly is 1.35.0 will try with that and come back with the results. Thanks for your response

**Comment by yatiac** [comment]
It worked, thank you, closing this.
