### ISSUE TITLE
 right: `true`: assets directory not found: "./res/assets/"', src/main.rs:143:5

### ISSUE THREAD

**Issue by yatiac** [valeriansaliou/vigil#23]
I am getting this error when runing vigil.exe.

I built it with cargo using the latest nightly build of rust. There were no errors when building so I am not sure what is missing.

**Comment by valeriansaliou** [comment]
Hi there. Windows is not supported unfortunately; Vigil is *NIX only.

**Comment by yatiac** [comment]
Just as a note, I manage to make it work by copying the res folder to /target/release
