### ISSUE TITLE
Golang reporter package

### ISSUE THREAD

**Issue by avelino** [valeriansaliou/vigil#3]
It would be important have go package (as it was made from JavaScript)

**Comment by valeriansaliou** [comment]
I'm open to contributions. You may build your own package based on the code from either:

* https://github.com/valeriansaliou/rs-vigil-reporter
* https://github.com/valeriansaliou/node-vigil-reporter

And submit it to me. I'll then update Vigil's README with a link to your Golang package.

**Comment by valeriansaliou** [comment]
Hi there! I've identified a strong need for Golang microservices monitoring. Thus, I'm working on it 😄 

The Golang Vigil Reporter library project has just been initialized. It will be completed by tomorrow. — https://github.com/valeriansaliou/go-vigil-reporter

**Comment by valeriansaliou** [comment]
Here you go: https://github.com/valeriansaliou/go-vigil-reporter/tree/v1.0.0
