### ISSUE TITLE
Update year in copyright notice

### ISSUE THREAD

**Issue by whalehub** [valeriansaliou/vigil#32]
I'm running the latest version of Vigil in Docker and the copyright notice at the bottom of my status page says 2018 instead of 2019. Is this something you could fix in the next version?

![vivaldi_2019-06-27_22-41-49](https://user-images.githubusercontent.com/44198148/60299400-e6b8eb00-992c-11e9-9bda-1b656f8e9113.png)

**Comment by valeriansaliou** [comment]
Thanks, done! Not sure why I would not have made it dynamic when first developing Vigil, but that was the case. It's now fully dynamic!
