### ISSUE TITLE
Deploying in ZEIT Now V2

### ISSUE THREAD

**Issue by aguilaair** [valeriansaliou/vigil#37]
I'm not able to deploy vigil on ZEIT Now. The now.json is:

`{
	"version": 2,
	"name": "vigil",
  "builds": [
    { "src": "Cargo.toml", "use": "@now/rust", "config": { "rust": "nightly" } }
  ]
}`

and fails with code 101: 
https://pastebin.com/yZMrBJxE

Any suggestions? Thanks!

**Comment by kuboon** [comment]
src should be *.rs file. Not Cargo.toml
https://github.com/mike-engel/now-rust/blob/master/README.md
