### ISSUE TITLE
RabbitMQ connexion

### ISSUE THREAD

**Issue by haris44** [valeriansaliou/vigil#49]
Hi,

I tried to use rabbitmq plugins,  but the probe.service.node not show any replica

```
[[probe.service.node]]

id = "ai.ocr"
label = "OCR Queued Messages"
mode = "push"
rabbitmq_queue = "ocr_process_dev"
```

![Capture d’écran 2020-03-24 à 17 27 01](https://user-images.githubusercontent.com/14200996/77452814-ad97a380-6df6-11ea-9f88-3f4f72be1345.png)

Thx

**Comment by valeriansaliou** [comment]
Hello there,

You’d need to push a status report from a Vigil reporter library in order for the RabbitMQ plugin to pull the queue size upon pushing data.

Cheers,

--

Valerian Saliou
CTO at Crisp <https://crisp.chat/>
