### ISSUE TITLE
Show replica name in tooltip when hovering replica item (opt-in option)

### ISSUE THREAD

**Issue by blissend** [valeriansaliou/vigil#53]
First of all, thanks so much for vigil. I have tried so many alternatives and vigil is the only one that works consistently and works best.

I do have a feature request however. It would be nice to be able to mark or show somehow which replica's is which on the web page. Doesn't have to give away sensitive info, could be a label or anything really. 

If this is by design let me know or already possible then just ignore me :D I think it may be useful sometimes to know in automated workflows what got added/removed or perhaps you don't want to alert but curious which replica has unusual latency (which I'm not sure why some replica's show latency and others none in that popup).

**Comment by valeriansaliou** [comment]
Hello there,

I'm currently not showing the replica name on the public Web page, as it could reveal which internal IP address or URL is being probed. I could add an option to toggle this on or off, with a default value set to "don't show replica name".

Would that do?

**Comment by blissend** [comment]
Understood. That would do it for me at least.

Would it make sense to allow each replica to have an optional label? So if I called replica 2 BlueWhale only those who know internally would understand.

**Comment by valeriansaliou** [comment]
That would make sense as well, let's go for that. On it.

**Comment by richnusgeeks** [comment]
+1 as looking for the clue which underlying server/alias/label is failing the test. FYI I'm using the status page for within company only runtime acceptance testing endpoint baked into those VMs (ranging from few to hundreds grouped into their respective categories through probe.service sections).

**Comment by verymilan** [comment]
I am confused... this milestone is done for a while now, doc seems not to mention that and commits around that time are not very descriptive..

**Comment by valeriansaliou** [comment]
This is not yet implemented.

**Comment by verymilan** [comment]
Thanks for letting me know :)

**Comment by gbonnefille** [comment]
What about setting the label in the URL, using the *fragment* part of the URL like `http://...#my_label`?
It could be use also for other URI, like ICMP or other.

As far as I know, the fragment part is not processed by server, but only by client. So, using it as a storage for label will never handicap some user to refer an existing service.

https://datatracker.ietf.org/doc/html/rfc3986#section-3.5

**Comment by erwandf** [comment]
Hi Valerian,
is there any update on this issue ? this would also be really useful for us.

Best regards,

**Comment by valeriansaliou** [comment]
Hey Erwan, thank you for the heads up! Given the interest into this feature, I'll be looking into it today/tomorrow :)

**Comment by erwandf** [comment]
Thanks, this is very nice of you !
