### ISSUE TITLE
DNS probe

### ISSUE THREAD

**Issue by foxcpp** [valeriansaliou/vigil#57]
Feature request, add ability to check availability and validity of responses of a DNS server.
Send predefined query to specified endpoint and validate that response contains expected record.

In my use case that would be `SOA dn42` query sent to recursive resolver with the expectation to see one SOA record in response.

**Comment by valeriansaliou** [comment]
That's a great idea, I'm keeping this open for future versions of Vigil.

**Comment by geek1011** [comment]
A workaround for this is to do a HTTP check on the Google DNS resolver (https://developers.google.com/speed/public-dns/docs/doh/json).

**Comment by valeriansaliou** [comment]
Shell scripts have been added in b9a83967e13e3e147cd284a63c9a643fd02edb5e ; you can now perform DNS checks using custom-built shell scripts; eg. using `dig` and comparing results.

The goal of this script probe feature is to encompass all those monitoring use cases that not all Vigil users require.
