### ISSUE TITLE
Auto refresh of the status page.

### ISSUE THREAD

**Issue by richnusgeeks** [valeriansaliou/vigil#60]
I moved to Vigil from another amazing monitorwall [Monitoror](https://github.com/monitoror/monitoror) as wanted to keep track of a lot of servers not only visually but with alerts too as those VMs having acceptance testing backed into those and exposed through a http endpoint. All seems great in case of Vigil except its status page doesn't refresh automatically like it happens in case of the Monitoror. Could the auto refresh be added here as well? Thanks!

**Comment by valeriansaliou** [comment]
Hello there!

I can confirm that Vigil indeed auto-refreshes, though only in the event that the status changes (eg. healthy to sick, healthy to dead, dead to healthy, etc...). I think that the refresh timer was set to something like 10-20 secs.
