### ISSUE TITLE
cargo configuration breaks non-nightly builds

### ISSUE THREAD

**Issue by philpennock** [valeriansaliou/vigil#7]
Using cargo 0.25.0 with both rustc 1.25.0 and rustc 1.24.1, the documented install instructions fail, in whatever deep dependency is tried first, because:

```
error: the optimizations s or z are only accepted on the nightly compiler
```

My rust knowledge is almost non-existent, but as far as I can tell, this is the vigil project's `Cargo.toml` having, in `[profile.release]`, `opt-level = "s"`.

**Comment by valeriansaliou** [comment]
Hi there! You need to use the nightly compiler to build Vigil. It’s not compatible with the stable one at the moment.

--

Valerian Saliou
CTO at Crisp & Enrich

**Comment by valeriansaliou** [comment]
All builds nicely if you remove that `opt-level` argument on `stable`?

**Comment by valeriansaliou** [comment]
Ah, yes. I have unfortunately no control on that dep.

On changing the `Cargo.toml` file yourself, it's perfectly fine.

**Comment by valeriansaliou** [comment]
Closing this, as this is unsolvable ATM (we depend on `rocket`, that depends on `pear_codegen`, that's nightly only).
