### ISSUE TITLE
Support for stable rust

### ISSUE THREAD

**Issue by tglman** [valeriansaliou/vigil#71]
Hi,

To build and run vigil is required nigthly rust, in many case this is fine but in some stable rust is required.
I did my own investigation, and the only reason why nighlty is required is for some compiler features that rocket requires, this should be fixed the next releases of rocket as the master of rocket is already compatible with stable rust: https://github.com/SergioBenitez/Rocket/issues/19#issuecomment-736637259 but this as today is yet not a good option, simply because this is not releases yet.

So i went a bit ahead and made a quick fork ([here](https://github.com/RustRome/vigil/tree/optional_rocket)) that make rocket optional, and then i did a server implementation using actix-web, that as i write it already run in rust stable (you can see the implementation [here](https://github.com/RustRome/vigil/blob/optional_rocket/src/responder/server.rs)).

What it's your take on this issue ? do you prefer wait for rocket to be stable ? do you like to have two possible server implementations? or maybe migrate to actix-web is already stable ?

Regards

**Comment by valeriansaliou** [comment]
Hello @tglman 

Thanks a ton for your work on migrating from Rocket to Actix! I was indeed waiting for Rocket to compile on stable, but this takes a bit of time, so I'm willing to fully migrate to Actix.

You may completely remove Rocket in your fork, and submit a PR, I'll greatly appreciate it 👍 

Thanks again!

**Comment by tglman** [comment]
Hi,

Here the PR with rocket that is replaced by actix-web: https://github.com/valeriansaliou/vigil/pull/72

Regards

**Comment by valeriansaliou** [comment]
Merged
