### ISSUE TITLE
Feature Request Inquiry: Pass in a custom tera html template.

### ISSUE THREAD

**Issue by CSP197** [valeriansaliou/vigil#73]
Hello -
I wanted to inquire if it would be possible to pass in a custom `index.tera` template file via the `config.cfg`.

I wanted to customize some of the text on the page as well as tweak how the replicas are rendered on the page without modifying the source code.

Thank you!

**Comment by valeriansaliou** [comment]
Hello!

I'd advise modifying the template right away, that's what I do in my case, as it should be seen as a "Vigil Theme", and is completely independent from the Vigil binary and thus the updates you may apply to it over time.

If breaking changes are introduced to the template, it'll be mentioned in https://github.com/valeriansaliou/vigil/releases
And, breaking changes, if any, should come as of a MAJOR semver bump.
