### ISSUE TITLE
Remove replica via HTTP

### ISSUE THREAD

**Issue by NikoGrano** [valeriansaliou/vigil#77]
To follow automatically scaling environment, additional replicas are created and destroyed time to time.

Example:
1. There is 3 replicas.
2. Traffic peaks and 3 additional replicas are created to match the demand.
3. Traffic no longer peaks and 3 created replicas are scaled down.
4. Vigil goes dead.

![image](https://user-images.githubusercontent.com/4658966/111911781-90300080-8a6f-11eb-944b-5be00d050ae4.png)

---

The example application in this picture is node app. I'm currently using [node-vigil-reporter](https://www.npmjs.com/package/vigil-reporter) there. When node application notices the replica is going down, it can manage the shutdown by calling something like

```javascript
var VigilReporter = require("vigil-reporter").VigilReporter;
var reporter = new VigilReporter({...});
reporter.destroy();
```

**However...** The endpoint to do "destroy" action is missing. I'm not familiar with Rust applications, tough I could learn it quickly, so I'm asking your opinion and help to implement this feature.

**Comment by valeriansaliou** [comment]
Hey Niko!

I totally understand the pain with that, I typically restart Vigil on my end to flush its replica memory.

I'd definitely accept a PR on to adding such a destroy method, which could be implemented over an HTTP DELETE on the Vigil Reporter API.

**Comment by NikoGrano** [comment]
Restarting Vigil in this is stypid. The changes on scaling happens multiple times in day. Flushing memory with restart is not a option.

Where is the data exactly stored at? I was checking the code, and I think it might be here:
https://github.com/valeriansaliou/vigil/blob/master/src/prober/manager.rs#L41

At least in some part of code there is `.insert` being called. Somehow need to figure where to delete. The HTTP method itself is pretty easy to implement.

**Comment by NikoGrano** [comment]
Ill try implement something. Ill be posting a PR today.

**Comment by NikoGrano** [comment]
@valeriansaliou Ready for review. I also made PR to the node library. 🤗

**Comment by valeriansaliou** [comment]
Merged.
