### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by Cosaquee** [valeriansaliou/vigil#8]
The project looks really nice but my main alerting and monitoring solution is Prometheus. I was thinking about introducing Vigil as a monitoring component due to the fact that blackbox_exporter (Prometheus own exporter to monitor HTTP / TCP services is hard to setup, needs a lot of relabelling etc). So if vigil would be scraping and collecting info about which service is down or not and would expose that in Prometheus metrics format it would be great.

So I`m just curious if you have something like that in mind?

**Comment by valeriansaliou** [comment]
Hi, sure!

Do you have an example of what Prometheus metrics data would look like, as generated by Vigil? I assume it's some kind of JSON or XML returned by an HTTP route by Vigil, is that right?

**Comment by Cosaquee** [comment]
Prometheus metrics are just plaintext exposed on some port. You can read more [here](https://prometheus.io/docs/instrumenting/writing_exporters/).

I wrote a super simple [prometheus exporter](https://github.com/Cosaquee/prometheus-port-exporter) in that checks if port is open or not(first time using rust so code quality is low) but you can see how it is made with help of [rust-prometheus](https://github.com/pingcap/rust-prometheus).

For now my projects exposes metrics in Prometheus format and it looks like this:

```
port_up{name="service1",port="8123"} 1
port_up{name="service2",port="9060"} 1
port_up{name="service3",port="8080"} 1
port_up{name="service4",port="9050"} 1
```

1 means port is open, 0 means something is wrong.

I need to play a little bit more with Vigil and I can write down my notes and ideas if you would be interested in them.

For know I just wanted to know if you are interested in exposing such metrics.

**Comment by valeriansaliou** [comment]
Sure! I'm interested. Come back w/ full notes and I can work out on an impl.

**Comment by valeriansaliou** [comment]
Dropping this feature, as Vigil aims at being a simple main monitoring solution; not designed for being a secondary solution.
