### ISSUE TITLE
Please add UDP support

### ISSUE THREAD

**Issue by verymilan** [valeriansaliou/vigil#81]
Hi there, i am running two services over udp only - publicly at least. I would be happy to be able to add them to vigil. :)

**Comment by valeriansaliou** [comment]
Hello there! Unfortunately UDP probes cannot be easily designed at that layer, as UDP is a connection-less protocol. Best IMHO would be to implement more application-layer probes for protocols using UDP, eg. DNS, as we can check at the DNS protocol level if we got an answer.

**Comment by verymilan** [comment]
I see, thanks, i gonna look for workarounds with vigil-local for now...
