### ISSUE TITLE
notifier "sick" status unclear and does not change to "healthy"

### ISSUE THREAD

**Issue by verymilan** [valeriansaliou/vigil#82]
Hi there, i've connected Vigil to Matrix (yay!), and today i have noticed that this night the "Status changed to: *SICK*" - but it does not tell me where and it did not change back to *HEALTHY*, but when i open the page, everything is green... .

**Comment by valeriansaliou** [comment]
That's normal, as SICK statuses are considered non-downtimes, and thus do now trigger a notification when going from SICK -> HEALTHY.

Here's a summary of what causes the notifier to kick in:

* Status changed from `HEALTHY` to `DEAD` (downtime);
* Status changed from `DEAD` to `HEALTHY` (recovery);
* Status changed from `DEAD` to `SICK` (recovery);
* Status is still `DEAD` (after reminder interval);

**Comment by verymilan** [comment]
I am sorry, but i am not sure if there might be a misunderstanding:
What i mean is the message at Matrix, which has no reference to any service. The statuspage shows everything as healthy, but there is no message telling me that "whatever" is back to healthy.

Previous "SICK" statuses have not triggered any statusmessage.
![Bildschirmfoto vom 2021-04-07 09-56-12](https://user-images.githubusercontent.com/10698140/113831364-d1225780-9787-11eb-9637-4eb63cd7b53d.png)

May this be about Vigil itself?

**Comment by valeriansaliou** [comment]
This is all normal. Vigil does not include nodes in HEALTHY or SICK alerts, it does only in DEAD.

**Comment by verymilan** [comment]
This is very unhandy as Vigil monitors multiple machines with multiple services. Please include this when messages are being sent.
A different monitoring now told me that actually the Matrix service (or some part of it) threw a 502 for a short amount of time - so a worker was sad during backups. With Vigil i would not have known this. 

Why do some SICK statuses trigger the notifier and some do not? Is this because of how long it was considered being sick?

**Comment by valeriansaliou** [comment]
See: https://github.com/valeriansaliou/vigil/issues/82#issuecomment-814677849

**Comment by verymilan** [comment]
> and thus do now trigger a notification when going from SICK -> HEALTHY.

so please change the wording if this was the case then.
other than that, please consider adding a reference to that message a feature request...
