### ISSUE TITLE
Please add an announcement feature of some sort

### ISSUE THREAD

**Issue by verymilan** [valeriansaliou/vigil#83]
The Crisp port shows a screenshot of a big fat announcement. I partially could imitate that by putting `custom_html` to the top, but that wouldn't be the same. I would also like to trigger the notifier with announcements and track maintenances/updates on maintenances.

Vigil is pretty cool but this is clearly missing... maybe Vigil could look for local Markdown files as a workaround for the missing backend?

**Comment by valeriansaliou** [comment]
That's not yet supported.

Note that Crisp Status is the commercial equivalent of Vigil, bundled into Crisp, with more support-oriented features.

**Comment by verymilan** [comment]
I know, please consider this a feature request. 
...i have just realized, that i could play with the `index.tera` in the meantime to avoid custom html above the navbar :thinking:

**Comment by valeriansaliou** [comment]
Closing this issue as announcement have been added since then: https://github.com/valeriansaliou/vigil#what-do-announcements-look-like
