### ISSUE TITLE
Customize request URL

### ISSUE THREAD

**Issue by hampsterx** [valeriansaliou/vigil#9]
```
fn proceed_replica_probe_http(url: &str, body_match: &Option<Regex>) -> bool {
    let url_bang = format!("{}?{}", url, time::now().to_timespec().sec);
```
Nice project, I have a couple of backend services that don't like having extraneous query params so I can't use them currently. I can understand you want to cache break the requests but this implementation prevents using requests with query params as well

**Comment by valeriansaliou** [comment]
Hi there. Yes, that's right! The solution would be to detect any existing query string parameters, and append the cache buster with '&' instead of '?'.

I'm accepting PRs!
