### ISSUE TITLE
Gotify URL has double slashes

### ISSUE THREAD

**Issue by ikaruswill** [valeriansaliou/vigil#94]
Even if I removed any trailing slashes from the gotify `app_url`, I'm still seeing double trailing slashes when vigil attempts to make the API call.

Config (Obfuscated)
```
[notify.gotify]

app_url = "https://gotify.example.com"
app_token = "sometoken"
```

Logs (Obfuscated)
```
Time: 03:59:19 UTC-0000
(DEBUG) - starting new connection: https://gotify.example.com/
(DEBUG) - resolving host="gotify.example.com"
(DEBUG) - connecting to 123.123.123.123:443
(DEBUG) - connected to 123.123.123.123:443
(DEBUG) - flushed 184 bytes
(DEBUG) - flushed 162 bytes
(DEBUG) - read 188 bytes
(DEBUG) - parsed 3 headers
(DEBUG) - incoming body is content-length (73 bytes)
(DEBUG) - incoming body completed
(DEBUG) - pooling idle connection for ("https", gotify.example.com)
(DEBUG) - response '404 Not Found' for https://gotify.example.com//message?token=sometoken
```

Is anyone else getting this? 

Unfortunately I have zero expertise in rust, so I'm unable to debug this in the code, but I do see that in `vigil/src/notifier/gotify.rs` there's a string interpolation that joins the `gotify.app_url.as_str()` result to a suffix with a hard-coded forward slash. Is it possible that it's causing the issue? 

I'm thinking perhaps we can change this to use Rust's built-in url joining for less headaches regardless if this is the cause.

**Comment by valeriansaliou** [comment]
Hello,

Thanks, indeed there was an issue. I've fixed them on master, can you please rebuild Vigil from master and let me know if that works now?

**Comment by ikaruswill** [comment]
Blazing fast work sir! Thanks for taking a look at this. It's late night here now so let me get back to you tomorrow after testing it.

**Comment by ikaruswill** [comment]
Hey @valeriansaliou thanks for the fix. I've built the image locally and confirmed gotify url is now fixed.

```
(DEBUG) - starting new connection: https://gotify.example.com/
(DEBUG) - resolving host="gotify.example.com"
(DEBUG) - connecting to 118.189.201.139:443
(DEBUG) - connected to 118.189.201.139:443
(DEBUG) - flushed 183 bytes
(DEBUG) - flushed 125 bytes
(DEBUG) - read 299 bytes
(DEBUG) - parsed 3 headers
(DEBUG) - incoming body is content-length (190 bytes)
(DEBUG) - incoming body completed
(DEBUG) - pooling idle connection for ("https", gotify.example.com)
(DEBUG) - response '200 OK' for https://gotify.example.com/message?token=sometoken
(DEBUG) - dispatched notification to provider: gotify
```

**Comment by ikaruswill** [comment]
By the ways, since this is fixed, @valeriansaliou would you release a hotfix version for this? 

I run vigil on a Kubernetes cluster at home for my family so I'm relying on your images on Docker Hub.

I would build my own fork but that would diverge from this repository.

**Comment by valeriansaliou** [comment]
I'll issue a release in a few moments yes.

**Comment by valeriansaliou** [comment]
Released https://github.com/valeriansaliou/vigil/releases/tag/v1.22.1
Binaries & Docker image are currently building and will be published in the next 5 minutes.
