### ISSUE TITLE
passing configuration flags as environment variables supported?

### ISSUE THREAD

**Issue by dminca** [valeriansaliou/vigil#97]
Can we pass some configuration bits as environment variables?

Common scenario for this would be passing sensitive info like `server.reporter_token`, in Kubernetes we can pull this from a `SealedSecret` ideally.

**Comment by valeriansaliou** [comment]
Hello there! It's not yet possible unfortunately, you'd need to have a configuration file builder set in the middle that would prepare & inject environment variables upon pod start, right before Vigil starts.

**Comment by dminca** [comment]
Thanks for the follow-up Valerian, I thought it was simpler than that; for example, some Java Spring Boot apps support that by default, let alone in Golang as well through the [spf13/viper](https://github.com/spf13/viper) lib without further tweaks.
